### PR TITLE
ugly hack to support incompatibility between matplotlib and wx 

### PR DESCRIPTION
**Pull request by bmaranville**
FigureManager is calling window.SetTitle, where window is now the same thing as frame, and only top-level windows have SetTitle in new wx versions, not Panel

### CODE REVIEW

**Comment by pkienzle** [comment]
Also needed in `refl1d.view.data_view.py` and `bumps.gui.plot_view.py`?

[Rule of three](https://en.wikipedia.org/wiki/Rule_of_three_(computer_programming)) says this needs to be refactored as a plot panel mixin...

**Comment by bmaranville** [comment]
It would be really nice if this would stop happening all the time.  wx and matplotlib do not play well together...

**Comment by bmaranville** [comment]
It looks like FigureManagerBase is expecting to be run in a Frame, instead of a Panel.

**Comment by bmaranville** [comment]
The mixin solution would require a release of bumps as well, since we build refl1d from the pypi bumps release.  Maybe I should split off the build for "unstable" so it uses the bumps "unstable" code as well, so we can fix things faster and get them to users.

**Comment by pkienzle** [comment]
If we fed the embedding upstream then it might be better maintained. Or create an embedding package hosted separately on pip so others can help maintain it. I'm not sure that would be less work though.

**Comment by bmaranville** [comment]
Actually I don't think this affects refl1d.view.data_view.py and bumps.gui.plot_view.py... they call FigureManagerBase through EmbeddedPylab, and not FIgureManager directly like model_view does. 

That might argue that model_view can be refactored to use EmbeddedPylab like the others do, but that would take quite a bit of time.

**Comment by bmaranville** [comment]
Ok, I was looking at the code wondering if we could replace FigureManager with FigureManagerBase in model_view, but... it turms out that the FigureManager created in the __init__ is never used!  There is no other reference to 'figmgr' in that file, or any other file in bumps or refl1d.

I tried commenting out the line self.figmgr = FigureManager(...) line, and refl1d gui still loads.  Is there some side effect from instantiating FigureManager that is necesary, or can we just remove it?

**Comment by pkienzle** [comment]
`FigureManager(canvas)` sets `canvas.manager` so it is doing something. It'll require quite a bit of checking to make sure all the figure interactions still work. For example, can you still pan and zoom in the profile window?

**Comment by bmaranville** [comment]
Zooming and panning in the profile view seems to work fine still.  What other interactions should I check?

**Comment by bmaranville** [comment]
Oh - right - all the interactors!  Trying them out now.

**Comment by bmaranville** [comment]
It seems to work fine, though if you'd rather we could just switch FigureManagerBase for FIgureManager and it would fix the conflict, at least for now.  Setting canvas.manager happens in FigureManagerBase.

FigureManagerBase calls self.set_title now, as of version 3.4.1 of matplotlib, but it does *not* implement set_title (just a stub) so it has no effect.  FigureManagerWx has set_title implemented, and calls self.window.SetTitle(), which is what triggered the bug.

**Comment by pkienzle** [comment]
Looking for `.manager` in matplotlib:
* `animation.py` - don't care
* `backend_bases.py` - for `full_screen_toggle()` but properly trapped
* `figure.py` - for `figure.show()` which we don't use.
* `pyplot.py` - for `figure()` and `get_current_figure_manager()` which we don't use.
* `widgets.py` - don't care

So it should be fine commented out, but we might have better future-proofing with `FigureManagerBase`.

**Comment by bmaranville** [comment]
Ok, I'll use FigureManagerBase and test.

**Comment by bmaranville** [comment]
Seems to work.  I think we can jettison this pull request and just make a two-line fix in master.

Apparently we can't convert a pull request to an issue (though the reverse is possible).  Should we keep it for posterity, or dump?

**Comment by glass-ships** [comment]
Is this branch safe to delete, if it's been implemented elsewhere?

**Pull request closed without merging**
